<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnNextCountyPage</name>
   <tag></tag>
   <elementGuidId>d10357ea-e517-4acf-be2f-1687d22d0d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;var a=function(){callGAEventReg('Next','Where You Live');return checkMutipleClick(this);if(window != window.top){var f = document.getElementById('j_id0:PKPageTemplate:form1');f.action += (f.action.indexOf('?') == -1 ? '?' : '&amp;');};};var b=function(){if(typeof jsfcljs == 'function'){jsfcljs(document.getElementById('j_id0:PKPageTemplate:form1'),'j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id175,j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id175,j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id176,NextButtonClicked','');}return false};return (a()==false) ? false : b();&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '#' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var a=function(){callGAEventReg('Next','Where You Live');return checkMutipleClick(this);if(window != window.top){var f = document.getElementById('j_id0:PKPageTemplate:form1');f.action += (f.action.indexOf('?') == -1 ? '?' : '&amp;');};};var b=function(){if(typeof jsfcljs == 'function'){jsfcljs(document.getElementById('j_id0:PKPageTemplate:form1'),'j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id175,j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id175,j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id176,NextButtonClicked','');}return false};return (a()==false) ? false : b();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>afbDarkBlueBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:PKPageTemplate:form1:navButtons:j_id167:j_id174&quot;)/a[@class=&quot;afbDarkBlueBtn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//span[contains(.,'What county')]/../..//select/../../../..//a[contains(text(),'Next')]</value>
   </webElementXpaths>
</WebElementEntity>
